# Generated by Django 6.0.4 on 2026-05-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total_price',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
