# Generated by Django 6.0.4 on 2026-05-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='temp_order_id', max_length=20, unique=True),
        ),
    ]
